<?php
    include "setup_session.php";
    if(isset($_GET['specialty'])){
        $_SESSION['cart'][0]++;
        header("location:../ordernow-ramen.php");
    }elseif(isset($_GET['miso'])){
        $_SESSION['cart'][1]++;
        header("location:../ordernow-ramen.php");
    }elseif(isset($_GET['karaka'])){
        $_SESSION['cart'][2]++;
        header("location:../ordernow-ramen.php");
    }elseif(isset($_GET['tonkotsu'])){
        $_SESSION['cart'][3]++;
        header("location:../ordernow-ramen.php");
    }
    elseif(isset($_GET['mazesoba'])){
        $_SESSION['cart'][4]++;
        header("location:../ordernow-ramen.php");
    }
    elseif(isset($_GET['tantanmen'])){
        $_SESSION['cart'][5]++;
        header("location:../ordernow-ramen.php");
    }
    elseif(isset($_GET['edamame'])){
        $_SESSION['cart'][6]++;
        header("location:../ordernow-sides.php");
    }
    elseif(isset($_GET['sashimi'])){
        $_SESSION['cart'][7]++;
        header("location:../ordernow-sides.php");
    }
    elseif(isset($_GET['chawanmushi'])){
        $_SESSION['cart'][8]++;
        header("location:../ordernow-sides.php");
    }
    elseif(isset($_GET['takoyaki'])){
        $_SESSION['cart'][9]++;
        header("location:../ordernow-sides.php");
    }
    elseif(isset($_GET['sushi'])){
        $_SESSION['cart'][10]++;
        header("location:../ordernow-sides.php");
    }
    elseif(isset($_GET['gyoza'])){
        $_SESSION['cart'][11]++;
        header("location:../ordernow-sides.php");
    }
    elseif(isset($_GET['citrus'])){
        $_SESSION['cart'][12]++;
        header("location:../ordernow-drinks.php");
    }
    elseif(isset($_GET['yuzu'])){
        $_SESSION['cart'][13]++;
        header("location:../ordernow-drinks.php");
    }
    elseif(isset($_GET['plum'])){
        $_SESSION['cart'][14]++;
        header("location:../ordernow-drinks.php");
    }
    elseif(isset($_GET['sake'])){
        $_SESSION['cart'][15]++;
        header("location:../ordernow-drinks.php");
    }
    elseif(isset($_GET['matcha'])){
        $_SESSION['cart'][16]++;
        header("location:../ordernow-drinks.php");
    }
    elseif(isset($_GET['houjicha'])){
        $_SESSION['cart'][17]++;
        header("location:../ordernow-drinks.php");
    }
?>